import type { EditorLayer, ImageLayer, TextLayer } from '../types/editor'

export interface SampleProject {
  id: string
  label: string
  presetId: string
  layers: EditorLayer[]
}

const textLayer = (
  overrides: Partial<TextLayer> & Pick<TextLayer, 'id' | 'text' | 'x' | 'y' | 'width' | 'height'>,
): TextLayer => ({
  type: 'text',
  name: overrides.id,
  locked: false,
  visible: true,
  rotation: 0,
  opacity: 1,
  shadow: { enabled: false, color: '#000000', blur: 10, offsetX: 5, offsetY: 5 },
  fontFamily: 'Noto Sans KR',
  fontSize: 14,
  color: '#111827',
  align: 'left',
  fontWeight: 'normal',
  fontStyle: 'normal',
  charSpacing: 0,
  lineHeight: 1.16,
  ...overrides,
})

const imageLayer = (
  overrides: Pick<ImageLayer, 'id' | 'src' | 'x' | 'y' | 'width' | 'height'>,
): ImageLayer => ({
  type: 'image',
  name: overrides.id,
  locked: false,
  visible: true,
  rotation: 0,
  opacity: 1,
  shadow: { enabled: false, color: '#000000', blur: 10, offsetX: 5, offsetY: 5 },
  ...overrides,
})

export const SAMPLE_PROJECTS: SampleProject[] = [
  {
    id: 'sample-business-card',
    label: '샘플: 명함',
    presetId: 'business-card',
    layers: [
      imageLayer({
        id: 'sample-card-photo',
        src: '/samples/headshot.jpg',
        x: 232,
        y: 20,
        width: 92,
        height: 149,
      }),
      textLayer({
        id: 'sample-card-brand',
        text: 'STUDIO KIM',
        x: 24,
        y: 20,
        width: 180,
        height: 14,
        fontSize: 9,
        color: '#2563eb',
      }),
      textLayer({
        id: 'sample-card-name',
        text: '김도윤',
        x: 24,
        y: 48,
        width: 190,
        height: 30,
        fontSize: 22,
        color: '#111827',
      }),
      textLayer({
        id: 'sample-card-title',
        text: 'Product Designer',
        x: 24,
        y: 80,
        width: 190,
        height: 16,
        fontSize: 11,
        color: '#6b7280',
      }),
      textLayer({
        id: 'sample-card-email',
        text: 'hello@studiokim.com',
        x: 24,
        y: 138,
        width: 200,
        height: 14,
        fontSize: 9,
        color: '#374151',
      }),
      textLayer({
        id: 'sample-card-phone',
        text: '010-1234-5678',
        x: 24,
        y: 154,
        width: 200,
        height: 14,
        fontSize: 9,
        color: '#374151',
      }),
    ],
  },
  {
    id: 'sample-poster-a4',
    label: '샘플: 포스터',
    presetId: 'poster-a4',
    layers: [
      textLayer({
        id: 'sample-poster-eyebrow',
        text: '2026 EXHIBITION',
        x: 97,
        y: 80,
        width: 600,
        height: 22,
        fontSize: 16,
        color: '#2563eb',
        align: 'center',
      }),
      textLayer({
        id: 'sample-poster-title',
        text: '빛과 색의 대화',
        x: 47,
        y: 130,
        width: 700,
        height: 100,
        fontFamily: 'Nanum Myeongjo',
        fontSize: 56,
        color: '#111827',
        align: 'center',
      }),
      textLayer({
        id: 'sample-poster-subtitle',
        text: '현대미술 특별전',
        x: 97,
        y: 250,
        width: 600,
        height: 32,
        fontSize: 22,
        color: '#4b5563',
        align: 'center',
      }),
      imageLayer({
        id: 'sample-poster-art',
        src: '/samples/poster-art.jpg',
        x: 19,
        y: 320,
        width: 756,
        height: 478,
      }),
      textLayer({
        id: 'sample-poster-info',
        text: '2026. 9. 12 – 11. 15   |   서울시립미술관',
        x: 97,
        y: 850,
        width: 600,
        height: 26,
        fontSize: 18,
        color: '#374151',
        align: 'center',
      }),
      textLayer({
        id: 'sample-poster-footer',
        text: '주최 · 서울문화재단',
        x: 97,
        y: 888,
        width: 600,
        height: 18,
        fontSize: 12,
        color: '#9ca3af',
        align: 'center',
      }),
    ],
  },
]
