import type { EditorLayer, ImageLayer, ShapeLayer, TextLayer } from '../types/editor'

export interface SampleProject {
  id: string
  label: string
  presetId: string
  layers: EditorLayer[]
}

const textLayer = (
  overrides: Partial<TextLayer> & Pick<TextLayer, 'id' | 'text' | 'x' | 'y' | 'width' | 'height'>,
): TextLayer => ({
  type: 'text',
  name: overrides.id,
  locked: false,
  visible: true,
  rotation: 0,
  opacity: 1,
  shadow: { enabled: false, color: '#000000', blur: 10, offsetX: 5, offsetY: 5 },
  border: { enabled: false, color: '#000000', width: 2 },
  flipX: false,
  flipY: false,
  blendMode: 'source-over',
  fontFamily: 'Noto Sans KR',
  fontSize: 14,
  color: '#111827',
  align: 'left',
  fontWeight: 'normal',
  fontStyle: 'normal',
  charSpacing: 0,
  lineHeight: 1.16,
  ...overrides,
})

const imageLayer = (
  overrides: Pick<ImageLayer, 'id' | 'src' | 'x' | 'y' | 'width' | 'height'>,
): ImageLayer => ({
  type: 'image',
  name: overrides.id,
  locked: false,
  visible: true,
  rotation: 0,
  opacity: 1,
  shadow: { enabled: false, color: '#000000', blur: 10, offsetX: 5, offsetY: 5 },
  border: { enabled: false, color: '#000000', width: 2 },
  flipX: false,
  flipY: false,
  blendMode: 'source-over',
  ...overrides,
})

const shapeLayer = (
  overrides: Partial<ShapeLayer> & Pick<ShapeLayer, 'id' | 'shape' | 'x' | 'y' | 'width' | 'height'>,
): ShapeLayer => ({
  type: 'shape',
  name: overrides.id,
  locked: false,
  visible: true,
  rotation: 0,
  opacity: 1,
  shadow: { enabled: false, color: '#000000', blur: 10, offsetX: 5, offsetY: 5 },
  border: { enabled: false, color: '#000000', width: 2 },
  flipX: false,
  flipY: false,
  blendMode: 'source-over',
  fill: '#e5e7eb',
  stroke: '#111827',
  strokeWidth: 0,
  ...overrides,
})

export const SAMPLE_PROJECTS: SampleProject[] = [
  {
    id: 'sample-business-card',
    label: '명함',
    presetId: 'business-card',
    layers: [
      imageLayer({
        id: 'sample-card-photo',
        src: '/samples/headshot.jpg',
        x: 232,
        y: 20,
        width: 92,
        height: 149,
      }),
      textLayer({
        id: 'sample-card-brand',
        text: 'STUDIO KIM',
        x: 24,
        y: 20,
        width: 180,
        height: 14,
        fontSize: 9,
        color: '#2563eb',
      }),
      textLayer({
        id: 'sample-card-name',
        text: '김도윤',
        x: 24,
        y: 48,
        width: 190,
        height: 30,
        fontSize: 22,
        color: '#111827',
      }),
      textLayer({
        id: 'sample-card-title',
        text: 'Product Designer',
        x: 24,
        y: 80,
        width: 190,
        height: 16,
        fontSize: 11,
        color: '#6b7280',
      }),
      textLayer({
        id: 'sample-card-email',
        text: 'hello@studiokim.com',
        x: 24,
        y: 138,
        width: 200,
        height: 14,
        fontSize: 9,
        color: '#374151',
      }),
      textLayer({
        id: 'sample-card-phone',
        text: '010-1234-5678',
        x: 24,
        y: 154,
        width: 200,
        height: 14,
        fontSize: 9,
        color: '#374151',
      }),
    ],
  },
  {
    id: 'sample-poster-a4',
    label: '포스터',
    presetId: 'poster-a4',
    layers: [
      textLayer({
        id: 'sample-poster-eyebrow',
        text: '2026 EXHIBITION',
        x: 97,
        y: 80,
        width: 600,
        height: 22,
        fontSize: 16,
        color: '#2563eb',
        align: 'center',
      }),
      textLayer({
        id: 'sample-poster-title',
        text: '빛과 색의 대화',
        x: 47,
        y: 130,
        width: 700,
        height: 100,
        fontFamily: 'Nanum Myeongjo',
        fontSize: 56,
        color: '#111827',
        align: 'center',
      }),
      textLayer({
        id: 'sample-poster-subtitle',
        text: '현대미술 특별전',
        x: 97,
        y: 250,
        width: 600,
        height: 32,
        fontSize: 22,
        color: '#4b5563',
        align: 'center',
      }),
      imageLayer({
        id: 'sample-poster-art',
        src: '/samples/poster-art.jpg',
        x: 19,
        y: 320,
        width: 756,
        height: 478,
      }),
      textLayer({
        id: 'sample-poster-info',
        text: '2026. 9. 12 – 11. 15   |   서울시립미술관',
        x: 97,
        y: 850,
        width: 600,
        height: 26,
        fontSize: 18,
        color: '#374151',
        align: 'center',
      }),
      textLayer({
        id: 'sample-poster-footer',
        text: '주최 · 서울문화재단',
        x: 97,
        y: 888,
        width: 600,
        height: 18,
        fontSize: 12,
        color: '#9ca3af',
        align: 'center',
      }),
    ],
  },
  {
    id: 'sample-social-post',
    label: '소셜 포스트',
    presetId: 'square-card',
    layers: [
      shapeLayer({
        id: 'sample-social-bg',
        shape: 'rectangle',
        x: 0,
        y: 0,
        width: 393,
        height: 393,
        fill: '#0ea5e9',
      }),
      shapeLayer({
        id: 'sample-social-circle-1',
        shape: 'ellipse',
        x: 250,
        y: -60,
        width: 200,
        height: 200,
        fill: '#ffffff',
        opacity: 0.12,
      }),
      shapeLayer({
        id: 'sample-social-circle-2',
        shape: 'ellipse',
        x: -50,
        y: 280,
        width: 160,
        height: 160,
        fill: '#ffffff',
        opacity: 0.1,
      }),
      textLayer({
        id: 'sample-social-headline',
        text: 'SUMMER SALE',
        x: 20,
        y: 150,
        width: 353,
        height: 44,
        fontSize: 34,
        fontWeight: 'bold',
        color: '#ffffff',
        align: 'center',
      }),
      textLayer({
        id: 'sample-social-subtitle',
        text: '최대 50% 할인',
        x: 20,
        y: 200,
        width: 353,
        height: 30,
        fontSize: 20,
        fontWeight: 'bold',
        color: '#ffffff',
        align: 'center',
      }),
      textLayer({
        id: 'sample-social-dates',
        text: '9.1 – 9.30',
        x: 20,
        y: 240,
        width: 353,
        height: 20,
        fontSize: 13,
        color: '#e0f2fe',
        align: 'center',
        charSpacing: 50,
      }),
      textLayer({
        id: 'sample-social-brand',
        text: 'STUDIO KIM',
        x: 20,
        y: 350,
        width: 353,
        height: 16,
        fontSize: 10,
        color: '#e0f2fe',
        align: 'center',
        charSpacing: 150,
      }),
    ],
  },
  {
    id: 'sample-invitation',
    label: '청첩장',
    presetId: 'square-card',
    layers: [
      shapeLayer({
        id: 'sample-invite-bg',
        shape: 'rectangle',
        x: 0,
        y: 0,
        width: 393,
        height: 393,
        fill: '#fbf4ec',
      }),
      textLayer({
        id: 'sample-invite-eyebrow',
        text: 'SAVE THE DATE',
        x: 20,
        y: 95,
        width: 353,
        height: 16,
        fontSize: 11,
        color: '#b08d57',
        align: 'center',
        charSpacing: 250,
      }),
      textLayer({
        id: 'sample-invite-names',
        text: '지훈 · 서연',
        x: 20,
        y: 140,
        width: 353,
        height: 44,
        fontFamily: 'Nanum Myeongjo',
        fontSize: 32,
        color: '#3f3f3f',
        align: 'center',
      }),
      shapeLayer({
        id: 'sample-invite-divider',
        shape: 'line',
        x: 157,
        y: 205,
        width: 80,
        height: 0,
        stroke: '#c9a875',
        strokeWidth: 1,
      }),
      textLayer({
        id: 'sample-invite-date',
        text: '2026년 11월 14일 토요일 오후 2시',
        x: 20,
        y: 222,
        width: 353,
        height: 18,
        fontSize: 13,
        color: '#555555',
        align: 'center',
      }),
      textLayer({
        id: 'sample-invite-venue',
        text: '그랜드 하얏트 서울 · 그랜드볼룸',
        x: 20,
        y: 252,
        width: 353,
        height: 16,
        fontSize: 11,
        color: '#9a9a9a',
        align: 'center',
      }),
    ],
  },
]
